FROM node:16.14.0
RUN npm i npm@latest -g
# RUN npm install -g npm@8.1.1
RUN mkdir -p /app
WORKDIR /app
COPY package*.json ./
RUN npm install 
COPY . . 
EXPOSE 8000
CMD ["yarn", "run","start:production"]